module.exports = {
  mongoURI: 'mongodb+srv://zapevoteam:DMPJTajgZylLANf4@botsdb-sjntb.mongodb.net/test?retryWrites=true',
  botName: 'jomashop',
  websourceid: 3,
  port: '3019',
  siteLink: 'https://www.jomashop.com/',
  brands: [
    'https://www.jomashop.com/a-lange-and-sohne-watches.html',
    'https://www.jomashop.com/alpina-watches.html',
    'https://www.jomashop.com/anonimo-watches.html',
    'https://www.jomashop.com/armand-nicolet-watches.html',
    'https://www.jomashop.com/arnold-and-son-watches.html',
    'https://www.jomashop.com/audemars-piguet-watches.html',
    'https://www.jomashop.com/ball-watches.html',
    'https://www.jomashop.com/bedat-watches.html',
    'https://www.jomashop.com/bell-and-ross-watches.html',
    'https://www.jomashop.com/blanpain-watches.html',
    'https://www.jomashop.com/breguet-watches.html',
    'https://www.jomashop.com/breitling-watches.html',
    'https://www.jomashop.com/bremont-watches.html',
    'https://www.jomashop.com/bvlgari-watches.html',
    'https://www.jomashop.com/carl-f-bucherer-watches.html',
    'https://www.jomashop.com/cartier-watches.html',
    'https://www.jomashop.com/chanel.html',
    'https://www.jomashop.com/charriol-watches.html',
    'https://www.jomashop.com/chopard-watches.html',
    'https://www.jomashop.com/corum.html',
    'https://www.jomashop.com/cvstos-watches.html',
    'https://www.jomashop.com/dewitt-watches.html',
    'https://www.jomashop.com/dior-watches.html',
    'https://www.jomashop.com/ebel-watches.html',
    'https://www.jomashop.com/eterna-watches.html',
    'https://www.jomashop.com/franck-muller-watches.html',
    'https://www.jomashop.com/frederique-constant-watches.html',
    'https://www.jomashop.com/gevril-watches.html',
    'https://www.jomashop.com/girard-perregaux.html',
    'https://www.jomashop.com/glashutte-watches.html',
    'https://www.jomashop.com/gucciwatches.html',
    'https://www.jomashop.com/hamilton.html',
    'https://www.jomashop.com/harry-winston-watches.html',
    'https://www.jomashop.com/heritor-watches.html',
    'https://www.jomashop.com/hermes-watches.html',
    'https://www.jomashop.com/hublotwatches.html',
    'https://www.jomashop.com/hyt-watches.html',
    'https://www.jomashop.com/iwc.html',
    'https://www.jomashop.com/jacob-and-co-watches.html',
    'https://www.jomashop.com/jaeger-lecoultre-watches.html',
    'https://www.jomashop.com/jaquet-droz-watches.html',
    'https://www.jomashop.com/junghans-watches.html',
    'https://www.jomashop.com/longines-watches.html',
    'https://www.jomashop.com/maurice-lacroix-watches.html',
    'https://www.jomashop.com/michele.html',
    'https://www.jomashop.com/mido-watches.html',
    'https://www.jomashop.com/milus-watches.html',
    'https://www.jomashop.com/montblanc-watches.html',
    'https://www.jomashop.com/omega-watches.html',
    'https://www.jomashop.com/oriswatches.html',
    'https://www.jomashop.com/panerai-watches.html',
    'https://www.jomashop.com/patek-philippe-watches.html',
    'https://www.jomashop.com/perrelet-watches.html',
    'https://www.jomashop.com/piaget-watches.html',
    'https://www.jomashop.com/rado-watches.html',
    'https://www.jomashop.com/raymond-weil-watches.html',
    'https://www.jomashop.com/revue-thommen-watches.html',
    'https://www.jomashop.com/richard-mille-watches.html',
    'https://www.jomashop.com/rolex.html',
    'https://www.jomashop.com/tissot.html',
    'https://www.jomashop.com/tudor-watches.html',
    'https://www.jomashop.com/ulysse-nardin-watches.html',
    'https://www.jomashop.com/vacheron-constantin-watches.html',
    'https://www.jomashop.com/zenith-watches.html',
  ],
};
